"""Project starter templates."""

from pathlib import Path

import typer
from rich.console import Console

console = Console()

TEMPLATES = {
    "customer-support": {
        "README.md": """# Customer Support Agent (Aegis)

This project was generated by `aegis new customer-support`.

## Setup

```bash
pip install aegis-memory[langchain]
export AEGIS_API_KEY=dev-key
```

## Run

```bash
python app.py
```
""",
        "app.py": """from aegis_memory.integrations.langchain import AegisMemory

memory = AegisMemory(
    api_key=\"dev-key\",
    agent_id=\"support-agent\",
    namespace=\"customer-support\",
)

print(\"Customer support template ready.\")
""",
        ".env.example": "AEGIS_API_KEY=dev-key\nAEGIS_API_URL=http://localhost:8000\n",
    }
}


def new(
    template: str = typer.Argument(..., help="Template name (e.g. customer-support)"),
    output_dir: Path = typer.Option(Path("."), "--output", "-o", help="Output directory"),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing files"),
):
    """Generate project boilerplate from a starter template."""
    if template not in TEMPLATES:
        available = ", ".join(sorted(TEMPLATES))
        raise typer.BadParameter(f"Unknown template '{template}'. Available: {available}")

    root = output_dir / template
    root.mkdir(parents=True, exist_ok=True)

    for name, content in TEMPLATES[template].items():
        target = root / name
        if target.exists() and not force:
            console.print(f"[yellow]Skipped existing file:[/yellow] {target}")
            continue
        target.write_text(content, encoding="utf-8")
        console.print(f"[green]Created[/green] {target}")

    console.print(f"\n[bold green]Template ready:[/bold green] {root}")
